theme: jekyll-theme-cayman
title: Bundle of Java projects
description: Couple of Java projects i did while studying Java at Faculty of Electrical Engineering and Computing


releases_url: https://github.com/aeoden96/java_FER_projects/releases
show_downloads: true

github:
  zip_url: http://example.com/download.zip

team_members:
  -
    name: "Mateo Martinjak"
    role: "project lead"
    start_date: "2016-02-01"
  -
    name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  -
    name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
