theme: jekyll-theme-cayman
title: Bundle of Java projects
description: Couple of Java projects i did while studying Java at Faculty of Electrical Engineering and Computing



team_members:
  -
    name: "Mateo Martinjak"
    role: "project lead"
    start_date: "2016-02-01"
  -
    name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  -
    name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
